# Generated by Django 5.2.6 on 2025-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
