# Generated by Django 5.2.6 on 2025-09-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactinfo_facebook_url_contactinfo_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='linkedin_url',
            new_name='youtube_url',
        ),
    ]
