# Generated by Django 5.2.6 on 2025-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_linkedin_url_contactinfo_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='iframe_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Embed URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('intro', 'Intro Video'), ('regular', 'Regular Video'), ('short', 'Short / Reel')], max_length=20),
        ),
    ]
