# Generated by Django 5.2.6 on 2025-09-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_video_youtube_url_video_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='iframe_url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
    ]
