# Generated by Django 5.2.6 on 2025-09-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrochurePage',
        ),
    ]
