# Generated by Django 5.2.6 on 2025-09-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_brochurepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='heyzine_link',
            field=models.URLField(blank=True, help_text='Embed link for Heyzine flipbook', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
