# Generated by Django 5.2.6 on 2025-09-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_introvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntroVideo',
        ),
    ]
