# Generated by Django 5.2.6 on 2025-09-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_introvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='video',
            field=models.FileField(blank=True, help_text='Upload MP4 (H.264) for best compatibility', null=True, upload_to='plants/videos/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
