# Generated by Django 5.2.6 on 2025-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_caretip_pdf_file_alter_about_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretip',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='caretip',
            name='image',
            field=models.ImageField(blank=True, upload_to='caretips/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='banner_image',
            field=models.ImageField(upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='video',
            field=models.FileField(blank=True, help_text='Upload MP4 (H.264) for best compatibility', null=True, upload_to='plants/videos/'),
        ),
    ]
